# Generated by Django 5.0.7 on 2024-07-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name='наименование',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=200, unique=True, verbose_name='слаг-имя'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        upload_to='images/category/',
                        verbose_name='изображение',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name='наименование',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=200, unique=True, verbose_name='слаг-имя'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        upload_to='images/product/',
                        verbose_name='изображение',
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name='цена'
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='владелец корзины',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='products.product',
                        verbose_name='продукт',
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name='наименование',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=200, unique=True, verbose_name='слаг-имя'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        upload_to='images/subcategory/',
                        verbose_name='изображение',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='products.category',
                        verbose_name='категория продукта',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'default_related_name': '%(class)s',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.subcategory',
                verbose_name='подкатегория продукта',
            ),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(
                fields=('owner', 'product'), name='unique_cart_product'
            ),
        ),
    ]
